### ISSUE TITLE
How can i use it on AWS EC2 with the same AMI as AWS Lambda?

### ISSUE THREAD

**Issue by WaterKnight1998** [cesmunoz/lambda-imagamagick-ghostscript#1]
Hey,

I need to run it on AWS EC2, i have created and instance with the same AMI as aws lambda amazon linux 2. How can I achieve that?

I just launched an instance of amazon ec2 and installe docker, when I execute make inside your folder all I get is next output `mkdir build` and after that the execution stops.

Best regards,
WaterKnight

**Comment by cesmunoz** [comment]
The reason of the repo is for creating al lambda layer.
If you want to adjust this to an AWS EC2 and docker, you'll need to adjust the makefile to create a docker image and a container with the imagemagick and ghostcript installed
